version: "2"

run:
  timeout: 5m
  issues-exit-code: 42

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  default: none
  settings:
    depguard:
      rules:
        no-direct-zerolog-log:
          list-mode: lax
          files:
            - "!**/internal/log/**"
            - "!**/internal/utils/closer.go"
          deny:
            - pkg: "github.com/rs/zerolog/log"
              desc: "use go.zpotify.ru/zpotify/internal/log instead"
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    grouper:
      const-require-single-const: true
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: true
      var-require-single-var: true
    iface:
      enable:
        - identical
        - unexported
    importas:
      # Do not allow unaliased imports of aliased packages.
      # Default: false
      no-unaliased: true
  enable:
    - govet
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dupword
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exptostd
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - goprintffuncname
#    - gosec # Whole repo works with exec | folders | files on disk
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - iotamixing
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd

    - nakedret
    - nilerr
    - nolintlint
    - noinlineerr
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA9003:"
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - forbidigo
        path: internal/io/std_printer.go
      - linters:
          - funlen
        text: "Test_"
    paths:
      - configs
      - node_modules
      - pkg/web/ZpotifyUI/node_modules
      - tests/mocks
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - configs
      - node_modules
      - pkg/web/ZpotifyUI/node_modules
