package env_config_generator

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"go.vervstack.ru/matreshka/pkg/matreshka"
	"go.vervstack.ru/matreshka/pkg/matreshka/environment"
)

func Test_GenerateEnvConfig(t *testing.T) {
	t.Parallel()

	t.Run("environment", func(t *testing.T) {
		t.Parallel()

		env := matreshka.Environment{
			environment.MustNewVariable("one", 1),
			environment.MustNewVariable("two", time.Second),
		}

		_, generatedFolder, err := NewGenerateEnvironmentConfigStruct(env)()
		require.NoError(t, err)

		expected := `
// Code generated by RedSock CLI. DO NOT EDIT.

package config

import ( 
     "time"
)

// EnvironmentConfig holds parsed configuration values for this section.
type EnvironmentConfig struct { 
    One int
    Two time.Duration
}
`[1:]
		require.Equal(t, expected, string(generatedFolder.Content))
	})
}
