package env_config_generator

import (
	_ "embed"
	"text/template"
)

const (
	genTag = "// Code generated by RedSock CLI. DO NOT EDIT."
)

var (
	//go:embed templates/config_struct.go.pattern
	structPattern  string
	structTemplate *template.Template
)

//nolint:gochecknoinits // one-time compile of embedded template into a package-level *template.Template value
func init() {
	structTemplate = template.Must(
		template.New("environment").
			Parse(structPattern))
}
