package config_generators

import (
	"testing"

	"github.com/stretchr/testify/require"

	"go.vervstack.ru/verv/plugins/project/go_project/patterns"
	"go.vervstack.ru/verv/tests"
)

var expectedSkeletonGoFile = []byte(`
// Code generated by RedSock CLI. DO NOT EDIT.

package config

import _ "embed"

//go:embed skeleton.yaml
var skeletonYAML []byte
`)[1:]

func TestGenConfigSkeleton_ContentProvided(t *testing.T) {
	t.Parallel()

	content := []byte("app_info:\n  name: my-app\n")

	goFile, yamlFile, err := newGenerateConfigSkeleton(content)()
	require.NoError(t, err)

	tests.CompareLongStrings(t, expectedSkeletonGoFile, goFile.Content)
	require.Equal(t, content, yamlFile.Content)
	require.Equal(t, patterns.ConfigSkeletonGoFileName, goFile.Name)
	require.Equal(t, patterns.ConfigSkeletonYamlFileName, yamlFile.Name)
}

func TestGenConfigSkeleton_NilContentFallsBackToStub(t *testing.T) {
	t.Parallel()

	goFile, yamlFile, err := newGenerateConfigSkeleton(nil)()
	require.NoError(t, err)

	tests.CompareLongStrings(t, expectedSkeletonGoFile, goFile.Content)
	//nolint:testifylint // exact-bytes invariant is the point of this assertion
	require.Equal(t, stubSkeletonYAML, yamlFile.Content)
}

func TestGenConfigSkeleton_EmptyContentFallsBackToStub(t *testing.T) {
	t.Parallel()

	goFile, yamlFile, err := newGenerateConfigSkeleton([]byte{})()
	require.NoError(t, err)

	tests.CompareLongStrings(t, expectedSkeletonGoFile, goFile.Content)
	//nolint:testifylint // exact-bytes invariant is the point of this assertion
	require.Equal(t, stubSkeletonYAML, yamlFile.Content)
}
